# Generated by Django 5.0.6 on 2024-06-04 20:27

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_delete_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Article Images', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='film',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='film',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Başlıq'),
        ),
    ]
